=== a41-official/dotrisk-criteria/eigenlayer/schema/main_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "category": {
      "anyOf": [
        { "type": "string" },
        {
          "type": "array",
          "items": { "type": "string" }
        }
      ]
    },
    "criteria": {
      "type": "object",
      "properties": {
        "slashing": {
          "type": "object",
          "properties": {
            "is_implemented": {
              "type": "boolean"
            },
            "url": {
              "anyOf": [
                { "type": "string", "format": "uri" },
                { "type": "string", "maxLength": 0 }
              ]
            }
          },
          "required": ["is_implemented", "url"]
        },
        "reward": {
          "type": "object",
          "properties": {
            "is_implemented": {
              "type": "boolean"
            },
            "url": {
              "anyOf": [
                { "type": "string", "format": "uri" },
                { "type": "string", "maxLength": 0 }
              ]
            }
          },
          "required": ["is_implemented", "url"]
        }
      }
    },
    "contact": {
      "type": "object",
      "properties": {
        "telegram": {
          "anyOf": [
            { "type": "string", "format": "uri" },
            { "type": "string", "maxLength": 0 }
          ]
        },
        "discord": {
          "anyOf": [
            { "type": "string", "format": "uri" },
            { "type": "string", "maxLength": 0 }
          ]
        }
      }
    }
  },
  "required": ["name", "category", "contact"]
}

=== a41-official/dotrisk-criteria/eigenlayer/sample/reward_slashing_policy_status.json
{
  "name": "example avs",
  "category": [
    "Social"
  ],
  "criteria": {
    "slashing": {
      "is_implemented": true,
      "url": "https://www.docs.example-avs.com/slashing"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://www.docs.example-avs.com/reward"
    }
  },
  "contact": {
    "telegram": "https://t.me/example-avs",
    "discord": "https://discord.gg/example-avs"
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x42f15f9e4df4994317453477e80e24797cc1a929/reward_slashing_policy_status.json
{
  "name": "Human Network",
  "category": [""],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.network.human.tech/overview/running-a-human-node"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.network.human.tech/usage-instructions/human-network-credits"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x852dd23ae808a20c48d7b7b03d23c3f5360928e1/reward_slashing_policy_status.json
{
  "name": "Silence Laboratories",
  "category": [],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.silencelaboratories.com/welcome"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.silencelaboratories.com/welcome"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xa3f64d3102a035db35c42a9001bbc83e08c7a366/reward_slashing_policy_status.json
{
  "name": "GoPlus",
  "category": [""],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://whitepaper.gopluslabs.io/goplus-network/ecosystem-role/avs-operator"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://whitepaper.gopluslabs.io/goplus-network/ecosystem-role/avs-operator"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x6201bc0a699e3b10f324204e6f8ecdd0983de227/reward_slashing_policy_status.json
{
  "name": "ETHGas",
  "category": [""],
  "criteria": {
    "slashing": {
      "is_implemented": true,
      "url": "https://docs.ethgas.com/actors-and-integrations/validators"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.ethgas.com/actors-and-integrations/validators"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xd25c2c5802198cb8541987b73a8db4c9bcae5cc7/reward_slashing_policy_status.json
{
  "name": "WitnessChain",
  "category": ["Security"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.witnesschain.com/infinity-watch/proof-of-location-mainnet/run-a-watchtower/eigenlayer-operators"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.witnesschain.com/infinity-watch/proof-of-location-mainnet/run-a-watchtower/eigenlayer-operators"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x2d86e90ed40a034c753931ee31b1bd5e1970113d/reward_slashing_policy_status.json
{
  "name": "UniFi AVS",
  "category": ["Rollup"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.puffer.fi/unifi-avs-intro"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.puffer.fi/unifi-avs-intro"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x6026b61bdd2252160691cb3f6005b6b72e0ec044/reward_slashing_policy_status.json
{
  "name": "Xterio",
  "category": ["Gaming"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://github.com/alt-research/mach-avs/blob/m2-dev/docs/RunOperator.md"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://github.com/alt-research/mach-avs/blob/m2-dev/docs/RunOperator.md"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}
