=== a41-official/dotrisk-criteria/eigenlayer/schema/main_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "category": {
      "anyOf": [
        { "type": "string" },
        {
          "type": "array",
          "items": { "type": "string" }
        }
      ]
    },
    "criteria": {
      "type": "object",
      "properties": {
        "slashing": {
          "type": "object",
          "properties": {
            "is_implemented": {
              "type": "boolean"
            },
            "url": {
              "anyOf": [
                { "type": "string", "format": "uri" },
                { "type": "string", "maxLength": 0 }
              ]
            }
          },
          "required": ["is_implemented", "url"]
        },
        "reward": {
          "type": "object",
          "properties": {
            "is_implemented": {
              "type": "boolean"
            },
            "url": {
              "anyOf": [
                { "type": "string", "format": "uri" },
                { "type": "string", "maxLength": 0 }
              ]
            }
          },
          "required": ["is_implemented", "url"]
        }
      }
    },
    "contact": {
      "type": "object",
      "properties": {
        "telegram": {
          "anyOf": [
            { "type": "string", "format": "uri" },
            { "type": "string", "maxLength": 0 }
          ]
        },
        "discord": {
          "anyOf": [
            { "type": "string", "format": "uri" },
            { "type": "string", "maxLength": 0 }
          ]
        }
      }
    }
  },
  "required": ["name", "category", "contact"]
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x1f2c296448f692af840843d993ffc0546619dcdb/reward_slashing_policy_status.json
{
  "name": "Cyber",
  "category": ["Social", "Rollup"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.cyber.co/"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.cyber.co/"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x3addeb54ddd43eb40235ec32dfa7928f28a44bb5/reward_slashing_policy_status.json
{
  "name": "Gasp",
  "category": [],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.gasp.xyz/"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.gasp.xyz/"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x9fc952bdcbb7daca7d420fa55b942405b073a89d/reward_slashing_policy_status.json
{
  "name": "Brevis Network",
  "category": ["ZK", "Coprocessor"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://github.com/Zellic/publications/blob/master/Brevis%20-%20Zellic%20Audit%20Report.pdf"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://github.com/Zellic/publications/blob/master/Brevis%20-%20Zellic%20Audit%20Report.pdf"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xbc77233855e3274e1903771675eb71e602d9dc2e/reward_slashing_policy_status.json
{
  "name": "Primev",
  "category": [],
  "criteria": {
    "slashing": {
      "is_implemented": true,
      "url": "https://docs.primev.xyz/v1.1.0/concepts/rewards-and-slashing/rewards-and-slashing"
    },
    "reward": {
      "is_implemented": true,
      "url": "https://docs.primev.xyz/v1.1.0/concepts/rewards-and-slashing/rewards-and-slashing"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xef2a435e5ee44b2041100ef8cbc8ae035166606c/reward_slashing_policy_status.json
{
  "name": "Aligned",
  "category": [],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.alignedlayer.com/"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.alignedlayer.com/"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x71a77037870169d47aad6c2c9360861a4c0df2bf/reward_slashing_policy_status.json
{
  "name": "Altlayer",
  "category": ["Rollup"],
  "criteria": {
    "slashing": {
      "is_implemented": true,
      "url": "https://docs.altlayer.io/altlayer-documentation/altlayer-facilitated-actively-validated-services/altlayer-mach-avs/operator-guide"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.altlayer.io/altlayer-documentation/altlayer-facilitated-actively-validated-services/altlayer-mach-avs/operator-guide"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/ava/reward_slashing_policy_status.json
{
  "name": "Ava Protocol",
  "category": ["Intent", "Privacy"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://avaprotocol.org/docs/ethereum/getting-started/eigenlayer-avs"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://avaprotocol.org/docs/ethereum/getting-started/eigenlayer-avs"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xf6f4a30eef7cf51ed4ee1415fb3bfdaf3694b0d2/reward_slashing_policy_status.json
{
  "name": "Precated",
  "category": [],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.predicate.io/operators/run"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.predicate.io/operators/run"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}
