=== a41-official/dotrisk-criteria/eigenlayer/schema/main_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "category": {
      "anyOf": [
        { "type": "string" },
        {
          "type": "array",
          "items": { "type": "string" }
        }
      ]
    },
    "criteria": {
      "type": "object",
      "properties": {
        "slashing": {
          "type": "object",
          "properties": {
            "is_implemented": {
              "type": "boolean"
            },
            "url": {
              "anyOf": [
                { "type": "string", "format": "uri" },
                { "type": "string", "maxLength": 0 }
              ]
            }
          },
          "required": ["is_implemented", "url"]
        },
        "reward": {
          "type": "object",
          "properties": {
            "is_implemented": {
              "type": "boolean"
            },
            "url": {
              "anyOf": [
                { "type": "string", "format": "uri" },
                { "type": "string", "maxLength": 0 }
              ]
            }
          },
          "required": ["is_implemented", "url"]
        }
      }
    },
    "contact": {
      "type": "object",
      "properties": {
        "telegram": {
          "anyOf": [
            { "type": "string", "format": "uri" },
            { "type": "string", "maxLength": 0 }
          ]
        },
        "discord": {
          "anyOf": [
            { "type": "string", "format": "uri" },
            { "type": "string", "maxLength": 0 }
          ]
        }
      }
    }
  },
  "required": ["name", "category", "contact"]
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xe8e59c6c8b56f2c178f63bcfc4ce5e5e2359c8fc/reward_slashing_policy_status.json
{
  "name": "Hyperlane",
  "category": ["Interoperability"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.hyperlane.xyz/docs/protocol/economic-security/hyperlane-avs"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.hyperlane.xyz/docs/protocol/economic-security/hyperlane-avs"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x22cac0e6a1465f043428e8aef737b3cb09d0eeda/reward_slashing_policy_status.json
{
  "name": "Lagrange ZK Prover",
  "category": ["ZK", "Coprocessor"],
  "criteria": {
    "slashing": {
      "is_implemented": true,
      "url": "https://github.com/Lagrange-Labs/docs/blob/main/docs/state-committees/slashing.md"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://github.com/Lagrange-Labs/docs"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0x83742c346e9f305dca94e20915ab49a483d33f3e/reward_slashing_policy_status.json
{
  "name": "K3 Labs",
  "category": [""],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.k3-labs.com/introduction/tech-documentation/operator-onboarding"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.k3-labs.com/introduction/tech-documentation/operator-onboarding"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xed2f4d90b073128ae6769a9a8d51547b1df766c8/reward_slashing_policy_status.json
{
  "name": "Omni Network",
  "category": ["Interoperability"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.omni.network/introduction/whitepaper"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.omni.network/introduction/whitepaper"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xce06c5fe42d22ff827a519396583fd9f5176e3d3/reward_slashing_policy_status.json
{
  "name": "Opacity",
  "category": ["ZK", "Security"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.opacity.network/"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.opacity.network/"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xb3e069fd6dda251acbde09eda547e0ab207016ee/reward_slashing_policy_status.json
{
  "name": "Ungate",
  "category": [],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://ungate.gitbook.io/ungate-wukong"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://ungate.gitbook.io/ungate-wukong"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xf7fcff55d5fdaf2c3bbeb140be5e62a2c7d26db3/reward_slashing_policy_status.json
{
  "name": "Openlayer",
  "category": ["Oracle"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://openlayer.gitbook.io/openlayer/openlayer-avs/how-openlayer-works"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://openlayer.gitbook.io/openlayer/openlayer-avs/how-openlayer-works"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}

=== a41-official/dotrisk-criteria/eigenlayer/mainnet/0xe5445838c475a2980e6a88054ff1514230b83aeb/reward_slashing_policy_status.json
{
  "name": "Automata",
  "category": ["Coprocessor"],
  "criteria": {
    "slashing": {
      "is_implemented": false,
      "url": "https://docs.ata.network/"
    },
    "reward": {
      "is_implemented": false,
      "url": "https://docs.ata.network/"
    }
  },
  "contact": {
    "telegram": "",
    "discord": ""
  }
}
